/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'landing-pages': LandingPage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  title: string;
  /**
   * Identifiant URL du QR code (ex: mon-artwork-2024)
   */
  slug: string;
  status: 'draft' | 'published';
  vertical: 'art' | 'immo' | 'vcard' | 'product' | 'feedback' | 'tourism';
  theme?: {
    /**
     * Code hexadécimal (ex: #2563eb)
     */
    primaryColor?: string | null;
    logo?: (number | null) | Media;
  };
  artData?: {
    artistName?: string | null;
    /**
     * Courte présentation de l'artiste (formation, style, influences…)
     */
    artistBio?: string | null;
    artistNationality?: string | null;
    /**
     * Ex: 1985
     */
    artistBirthYear?: string | null;
    /**
     * Ex: 2024 ou 2022–2024
     */
    year?: string | null;
    /**
     * Ex: Huile sur toile, Aquarelle, Sculpture bronze…
     */
    medium?: string | null;
    /**
     * Ex: 80 × 60 cm
     */
    dimensions?: string | null;
    series?: string | null;
    /**
     * Ex: 3/10, Pièce unique, Épreuve d'artiste
     */
    edition?: string | null;
    /**
     * Ex: Certificat signé, Avec COA, Sans certificat
     */
    certificate?: string | null;
    /**
     * Note de l'artiste, contexte de création, démarche artistique…
     */
    description?: string | null;
    price?: number | null;
    currency?: ('EUR' | 'USD' | 'GBP' | 'CHF') | null;
    available?: boolean | null;
    sold?: boolean | null;
    exhibitionName?: string | null;
    exhibitionLocation?: string | null;
    /**
     * Ex: 15 jan. – 10 mars 2025
     */
    exhibitionDates?: string | null;
    videoUrl?: string | null;
    audioGuideUrl?: string | null;
    /**
     * Ex: @nom_artiste ou nom_artiste
     */
    instagramUsername?: string | null;
    websiteUrl?: string | null;
    /**
     * Lien vers la boutique en ligne ou la galerie
     */
    shopUrl?: string | null;
    contactEmail?: string | null;
  };
  immoData?: {
    propertyType?: ('apartment' | 'house' | 'gite' | 'villa' | 'studio') | null;
    address?: string | null;
    city?: string | null;
    price?: number | null;
    surface?: number | null;
    rooms?: number | null;
    dpe?: ('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G') | null;
    bookingUrl?: string | null;
    /**
     * Message personnalisé affiché en haut de la page d'accueil
     */
    welcomeMessage?: string | null;
    /**
     * Ex: 15h00
     */
    checkInTime?: string | null;
    /**
     * Ex: 11h00
     */
    checkOutTime?: string | null;
    /**
     * Emplacement des clés, code de la boîte à clé, digicode, etc.
     */
    checkInInstructions?: string | null;
    wifiName?: string | null;
    wifiPassword?: string | null;
    /**
     * Règles à respecter (pas de fumée, horaires calme, etc.)
     */
    houseRules?: string | null;
    /**
     * Ajoutez un équipement par ligne (ex: Piscine, Parking, WiFi, Lave-vaisselle…)
     */
    amenities?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Restaurants, randonnées, activités à faire dans les environs
     */
    localTips?: string | null;
    hostName?: string | null;
    hostPhone?: string | null;
    hostEmail?: string | null;
    /**
     * Numéro à appeler en cas de problème (ex: 15, 18, 112 ou numéro direct)
     */
    emergencyPhone?: string | null;
  };
  vcardData?: {
    fullName?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    jobTitle?: string | null;
    company?: string | null;
    /**
     * Courte présentation affichée sur la carte
     */
    bio?: string | null;
    phone?: string | null;
    email?: string | null;
    website?: string | null;
    address?: string | null;
    phoneWork?: string | null;
    emailWork?: string | null;
    linkedinUrl?: string | null;
    twitterUrl?: string | null;
    instagramUrl?: string | null;
    githubUrl?: string | null;
    youtubeUrl?: string | null;
    /**
     * Lien vers votre page de réservation (Calendly, Cal.com, etc.)
     */
    calendlyUrl?: string | null;
    /**
     * Ex: #1e3a5f — laissez vide pour utiliser la couleur de marque
     */
    coverColor?: string | null;
  };
  productData?: {
    productName?: string | null;
    brandName?: string | null;
    modelNumber?: string | null;
    description?: string | null;
    manualUrl?: string | null;
    videoTutorialUrl?: string | null;
    troubleshootingUrl?: string | null;
    /**
     * Ex: 2 ans, Garantie à vie
     */
    warrantyDuration?: string | null;
    warrantyDetails?: string | null;
    registrationUrl?: string | null;
    supportEmail?: string | null;
    supportPhone?: string | null;
    quickStartSteps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  feedbackData?: {
    companyName?: string | null;
    heading?: string | null;
    subheading?: string | null;
    googleReviewUrl?: string | null;
    tripadvisorUrl?: string | null;
    trustpilotUrl?: string | null;
    customReviewUrl?: string | null;
    /**
     * Ex: Facebook, Avis Vérifiés…
     */
    customReviewLabel?: string | null;
    enableDirectForm?: boolean | null;
    directFormEmail?: string | null;
    promptQuestion?: string | null;
  };
  tourismData?: {
    placeName?: string | null;
    locationName?: string | null;
    /**
     * Ex: Moyen Âge, XVIIe siècle, Art déco
     */
    historicPeriod?: string | null;
    description?: string | null;
    audioGuideUrl?: string | null;
    videoUrl?: string | null;
    latitude?: string | null;
    longitude?: string | null;
    address?: string | null;
    openingHours?: string | null;
    /**
     * Ex: Gratuit, 12€ adulte / 8€ réduit
     */
    entryFee?: string | null;
    websiteUrl?: string | null;
    contactPhone?: string | null;
    pointsOfInterest?:
      | {
          name: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  vertical?: T;
  theme?:
    | T
    | {
        primaryColor?: T;
        logo?: T;
      };
  artData?:
    | T
    | {
        artistName?: T;
        artistBio?: T;
        artistNationality?: T;
        artistBirthYear?: T;
        year?: T;
        medium?: T;
        dimensions?: T;
        series?: T;
        edition?: T;
        certificate?: T;
        description?: T;
        price?: T;
        currency?: T;
        available?: T;
        sold?: T;
        exhibitionName?: T;
        exhibitionLocation?: T;
        exhibitionDates?: T;
        videoUrl?: T;
        audioGuideUrl?: T;
        instagramUsername?: T;
        websiteUrl?: T;
        shopUrl?: T;
        contactEmail?: T;
      };
  immoData?:
    | T
    | {
        propertyType?: T;
        address?: T;
        city?: T;
        price?: T;
        surface?: T;
        rooms?: T;
        dpe?: T;
        bookingUrl?: T;
        welcomeMessage?: T;
        checkInTime?: T;
        checkOutTime?: T;
        checkInInstructions?: T;
        wifiName?: T;
        wifiPassword?: T;
        houseRules?: T;
        amenities?:
          | T
          | {
              name?: T;
              id?: T;
            };
        localTips?: T;
        hostName?: T;
        hostPhone?: T;
        hostEmail?: T;
        emergencyPhone?: T;
      };
  vcardData?:
    | T
    | {
        fullName?: T;
        firstName?: T;
        lastName?: T;
        jobTitle?: T;
        company?: T;
        bio?: T;
        phone?: T;
        email?: T;
        website?: T;
        address?: T;
        phoneWork?: T;
        emailWork?: T;
        linkedinUrl?: T;
        twitterUrl?: T;
        instagramUrl?: T;
        githubUrl?: T;
        youtubeUrl?: T;
        calendlyUrl?: T;
        coverColor?: T;
      };
  productData?:
    | T
    | {
        productName?: T;
        brandName?: T;
        modelNumber?: T;
        description?: T;
        manualUrl?: T;
        videoTutorialUrl?: T;
        troubleshootingUrl?: T;
        warrantyDuration?: T;
        warrantyDetails?: T;
        registrationUrl?: T;
        supportEmail?: T;
        supportPhone?: T;
        quickStartSteps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  feedbackData?:
    | T
    | {
        companyName?: T;
        heading?: T;
        subheading?: T;
        googleReviewUrl?: T;
        tripadvisorUrl?: T;
        trustpilotUrl?: T;
        customReviewUrl?: T;
        customReviewLabel?: T;
        enableDirectForm?: T;
        directFormEmail?: T;
        promptQuestion?: T;
      };
  tourismData?:
    | T
    | {
        placeName?: T;
        locationName?: T;
        historicPeriod?: T;
        description?: T;
        audioGuideUrl?: T;
        videoUrl?: T;
        latitude?: T;
        longitude?: T;
        address?: T;
        openingHours?: T;
        entryFee?: T;
        websiteUrl?: T;
        contactPhone?: T;
        pointsOfInterest?:
          | T
          | {
              name?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}